### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by MakeBetterMe** [leitingting08/sum-ui#2]
每个组件都是装的element-ui的全量css吗

**Comment by leitingting08** [comment]
这个问题确实是有待优化的，这样对 element-plus 不会有依赖，但是不全量引入的话项目中引用组件的时候样式不对，所以就先这样写了...

**Comment by MakeBetterMe** [comment]
组件写的蛮好的，期待更新

**Comment by leitingting08** [comment]
@MakeBetterMe  已优化~ 
element-plus也更新到正式版啦
