### ISSUE TITLE
希望该脚手架支持tailwindcss框架

### ISSUE THREAD

**Issue by Sunrise1970** [leitingting08/sum-ui#3]
业务系统使用了tailwincss框架，现在想使用该脚手架快速开发业务组件库，自己按照tailwincss安装了相关依赖并配置如下内容不生效，希望官方能提供帮助~
![image](https://user-images.githubusercontent.com/15205625/168606963-d1a9589b-cf8e-42f3-b12e-edbc1e15a6a7.png)
![image](https://user-images.githubusercontent.com/15205625/168607005-e20e060c-f658-4ac9-bf80-d6c06275c9aa.png)

**Comment by leitingting08** [comment]
这个是因为rollup里配置的是打包后的结果，要看打包后的样式是否生效的话，可以本地项目软连接调试看看能不能生效。
下面截图这里的是vuepress开发预览当然不会在这里生效，如果想要预览也生效需要对vuepress（docs/.vuepress下）进行tailwindcss的相关配置才行。

**Comment by Sunrise1970** [comment]
![image](https://user-images.githubusercontent.com/15205625/168974086-68229ec8-7f3c-4667-8dd2-4640be60365a.png)
1、打包出来的css文件是包含tw的样式代码的，说明rollup.config.js的配置没啥问题，同时改组件在项目引用使用的tw样式也是生效的。

2、.vueprecss下面我之前有尝试过配置，但是貌似不生效：
![image](https://user-images.githubusercontent.com/15205625/168974570-5c3e81db-503c-4716-965a-a49802d9eca0.png)
![image](https://user-images.githubusercontent.com/15205625/168974662-6d2330ea-e212-4c4d-86a7-48dfa7ba4dea.png)

现在就是文档预览组件这块的tw配置有点问题，不知道咋配置

**Comment by leitingting08** [comment]
@Sunrise1970   已支持
